export const GAME_CONFIG = {
    VIEWPORT: {
        LOGICAL_WIDTH: 960,
        LOGICAL_HEIGHT: 540,
        TARGET_FPS: 30,
        FRAME_TIME_MS: 1000 / 30,
    },
    LOGGING: {
        ENABLED: false,
        PERF_REPORT_INTERVAL_MS: 2000,
    },
    LIMITS: {
        MAX_ENEMIES: 5,
        MAX_PROJECTILES: 4,
        MAX_FLOATING_DAMAGES: 3,
    },
    PHYSICS: {
        PLAYER_SPEED: 260,
        PLAYER_DASH_SPEED: 620,
        DASH_DURATION_MS: 200,
        DASH_COOLDOWN_MS: 1800,
        ENEMY_BASE_SPEED: 130,
        PROJECTILE_BASE_SPEED: 520,
        PLAYER_RADIUS: 24,
        ENEMY_RADIUS: 22,
        PROJECTILE_RADIUS: 10,
        BOUNDARY_PADDING: 32,
        KNOCKBACK_FORCE: 180,
    },
    COMBAT: {
        CRITICAL_MULTIPLIER: 2.0,
        EFFECTIVE_MULTIPLIER: 2.0,
        NEUTRAL_MULTIPLIER: 1.0,
        RESISTED_MULTIPLIER: 0.5,
        IMMUNE_MULTIPLIER: 0.0,
        MAX_ULTIMATE_ENERGY: 100,
        ENERGY_PER_BASIC_ATTACK: 15,
        ENERGY_PER_SKILL_HIT: 20,
        ENERGY_PER_KILL: 30,
        ATTACK_COOLDOWN_MS: 280,
        SKILL_1_COOLDOWN_MS: 2500,
        SKILL_2_COOLDOWN_MS: 5000,
        INVULNERABILITY_AFTER_HIT_MS: 600,
        AUTO_ATTACK_INTERVAL_MS: 600,
    },
    CONTROLS: {
        JOYSTICK_BASE_RADIUS: 64,
        JOYSTICK_KNOB_RADIUS: 28,
        JOYSTICK_DEADZONE: 0.15,
        JOYSTICK_BOTTOM_OFFSET: 36,
        JOYSTICK_LEFT_OFFSET: 48,
        ATTACK_BUTTON_SIZE: 72,
        SKILL_BUTTON_SIZE: 54,
        DASH_BUTTON_SIZE: 50,
        ULTIMATE_BUTTON_SIZE: 62,
        ACTIONS_BOTTOM_OFFSET: 32,
        ACTIONS_RIGHT_OFFSET: 40,
    },
    UI: {
        HP_BAR_WIDTH: 200,
        HP_BAR_HEIGHT: 16,
        ENERGY_BAR_WIDTH: 200,
        ENERGY_BAR_HEIGHT: 8,
        BORDER_RADIUS_SM: 6,
        BORDER_RADIUS_MD: 12,
        BORDER_RADIUS_LG: 18,
    },
    COLORS: {
        VOID_BG: '#0B0C10',
        ARENA_FLOOR: '#1F2833',
        ARENA_BORDER: '#45A29E',
        CYAN_ACCENT: '#66FCF1',
        HEALTH_BAR: '#E63946',
        SHIELD_DASH: '#457B9D',
        ULTIMATE_GAUGE: '#F4A261',
        HITBOX_PLAYER: 'rgba(102, 252, 241, 0.45)',
        HITBOX_ENEMY: 'rgba(230, 57, 70, 0.45)',
        TEXT_PRIMARY: '#FFFFFF',
        TEXT_SECONDARY: '#C5C6C7',
        CRITICAL_TEXT: '#FFD166',
        JOYSTICK_BASE: 'rgba(31, 40, 51, 0.75)',
        JOYSTICK_KNOB: '#66FCF1',
        BUTTON_BG: 'rgba(31, 40, 51, 0.85)',
        BUTTON_BORDER: '#45A29E',
        BUTTON_PRESSED: '#66FCF1',
    },
    TYPE_ADVANTAGE: {
        fire: { grass: 2.0, ice: 2.0, bug: 2.0, steel: 2.0, water: 0.5, fire: 0.5, rock: 0.5, dragon: 0.5, ghost: 1.0 },
        water: { fire: 2.0, ground: 2.0, rock: 2.0, water: 0.5, grass: 0.5, dragon: 0.5 },
        grass: { water: 2.0, ground: 2.0, rock: 2.0, fire: 0.5, grass: 0.5, poison: 0.5, flying: 0.5, bug: 0.5, dragon: 0.5, steel: 0.5 },
        electric: { water: 2.0, flying: 2.0, electric: 0.5, grass: 0.5, dragon: 0.5, ground: 0.0 },
        normal: { rock: 0.5, steel: 0.5, ghost: 0.0 },
    } as Record<string, Record<string, number>>,
} as const;

export type GameConfig = typeof GAME_CONFIG;